### ISSUE TITLE
Use `ark_std::test_rng` for tests

### ISSUE THREAD

**Issue by weikengchen** [FindoraNetwork/zei#139]
Many of the tests in this library use a ChaCha20 random number generator with a fixed seed. In other words, our test random number generator is deterministic. Although it facilitates debugging, we are concerned about how strong such testing is. 

A solution is to do the following:
- `pub use ark_std::test_rng` in `zei-algebra`
- make sure that the `std` feature is on by default and propagates correctly in the Zei library
- replace ChaCha20Rng in tests with this

If we use a deterministic `ChaCha20Rng` in code that is not about tests. We should also label it, so we track our use of deterministic random number generator---they are okay for URS.

Assigned to @confuseSUN

**Comment by findora-crypto** [comment]
Closes by #140
